// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kubernetes

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// StorageClass used to store the data.
	// +kubebuilder:default:="replicated"
	StorageClass string `json:"storageClass"`
	// Worker nodes configuration map.
	// +kubebuilder:default:={"md0":{"ephemeralStorage":"20Gi","gpus":{},"instanceType":"u1.medium","maxReplicas":10,"minReplicas":0,"resources":{},"roles":{"ingress-nginx"}}}
	NodeGroups map[string]NodeGroup `json:"nodeGroups,omitempty"`
	// Kubernetes major.minor version to deploy
	// +kubebuilder:default:="v1.35"
	Version Version `json:"version"`
	// External hostname for Kubernetes cluster. Defaults to `<cluster-name>.<tenant-host>` if empty.
	// +kubebuilder:default:=""
	Host string `json:"host"`
	// Cluster addons configuration.
	// +kubebuilder:default:={}
	Addons Addons `json:"addons"`
	// Kubernetes control-plane configuration.
	// +kubebuilder:default:={}
	ControlPlane ControlPlane `json:"controlPlane"`
	// Optional image overrides for air-gapped or rate-limited registries.
	// +kubebuilder:default:={}
	Images Images `json:"images"`
}

type APIServer struct {
	// CPU and memory resources for API Server.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="u1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Addons struct {
	// Cert-manager addon.
	// +kubebuilder:default:={}
	CertManager CertManagerAddon `json:"certManager"`
	// Cilium CNI plugin.
	// +kubebuilder:default:={}
	Cilium CiliumAddon `json:"cilium"`
	// CoreDNS addon.
	// +kubebuilder:default:={}
	Coredns CoreDNSAddon `json:"coredns"`
	// FluxCD GitOps operator.
	// +kubebuilder:default:={}
	Fluxcd FluxCDAddon `json:"fluxcd"`
	// Gateway API addon.
	// +kubebuilder:default:={}
	GatewayAPI GatewayAPIAddon `json:"gatewayAPI"`
	// NVIDIA GPU Operator.
	// +kubebuilder:default:={}
	GpuOperator GPUOperatorAddon `json:"gpuOperator"`
	// Ingress-NGINX controller.
	// +kubebuilder:default:={}
	IngressNginx IngressNginxAddon `json:"ingressNginx"`
	// Monitoring agents.
	// +kubebuilder:default:={}
	MonitoringAgents MonitoringAgentsAddon `json:"monitoringAgents"`
	// Velero backup/restore addon.
	// +kubebuilder:default:={}
	Velero VeleroAddon `json:"velero"`
	// Vertical Pod Autoscaler.
	// +kubebuilder:default:={}
	VerticalPodAutoscaler VerticalPodAutoscalerAddon `json:"verticalPodAutoscaler"`
}

type CertManagerAddon struct {
	// Enable cert-manager.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type CiliumAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type ControlPlane struct {
	// API Server configuration.
	// +kubebuilder:default:={}
	ApiServer APIServer `json:"apiServer"`
	// Controller Manager configuration.
	// +kubebuilder:default:={}
	ControllerManager ControllerManager `json:"controllerManager"`
	// Konnectivity configuration.
	// +kubebuilder:default:={}
	Konnectivity Konnectivity `json:"konnectivity"`
	// Number of control-plane replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Scheduler configuration.
	// +kubebuilder:default:={}
	Scheduler Scheduler `json:"scheduler"`
}

type ControllerManager struct {
	// CPU and memory resources for Controller Manager.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="s1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type CoreDNSAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type FluxCDAddon struct {
	// Enable FluxCD.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GPU struct {
	// Name of GPU, such as "nvidia.com/AD102GL_L40S".
	Name string `json:"name"`
}

type GPUOperatorAddon struct {
	// Enable GPU Operator.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GatewayAPIAddon struct {
	// Enable Gateway API.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
}

type Images struct {
	// Image used by the wait-for-kubeconfig init container. Empty falls back to images/busybox.tag.
	// +kubebuilder:default:=""
	WaitForKubeconfig string `json:"waitForKubeconfig,omitempty"`
}

type IngressNginxAddon struct {
	// Enable the controller (requires nodes labeled `ingress-nginx`).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Method to expose the controller. Allowed values: `Proxied`, `LoadBalancer`.
	// +kubebuilder:default:="Proxied"
	ExposeMethod IngressNginxExposeMethod `json:"exposeMethod"`
	// Domains routed to this tenant cluster when `exposeMethod` is `Proxied`.
	// +kubebuilder:default:={}
	Hosts []string `json:"hosts,omitempty"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Konnectivity struct {
	// Konnectivity Server configuration.
	// +kubebuilder:default:={}
	Server KonnectivityServer `json:"server"`
}

type KonnectivityServer struct {
	// CPU and memory resources for Konnectivity.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="s1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type MonitoringAgentsAddon struct {
	// Enable monitoring agents.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type NodeGroup struct {
	// Ephemeral storage size.
	// +kubebuilder:default:="20Gi"
	EphemeralStorage resource.Quantity `json:"ephemeralStorage"`
	// List of GPUs to attach (NVIDIA driver requires at least 4 GiB RAM).
	Gpus []GPU `json:"gpus,omitempty"`
	// Virtual machine instance type.
	// +kubebuilder:default:="u1.medium"
	InstanceType string `json:"instanceType"`
	// Maximum number of replicas.
	// +kubebuilder:default:=10
	MaxReplicas int `json:"maxReplicas"`
	// Minimum number of replicas.
	// +kubebuilder:default:=0
	MinReplicas int `json:"minReplicas"`
	// CPU and memory resources for each worker node.
	Resources Resources `json:"resources"`
	// List of node roles.
	Roles []string `json:"roles,omitempty"`
}

type Resources struct {
	// CPU available.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Scheduler struct {
	// CPU and memory resources for Scheduler.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="s1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type VeleroAddon struct {
	// Enable Velero.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type VerticalPodAutoscalerAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

// +kubebuilder:validation:Enum="Proxied";"LoadBalancer"
type IngressNginxExposeMethod string

// +kubebuilder:validation:Enum="s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v1.35";"v1.34";"v1.33";"v1.32";"v1.31";"v1.30"
type Version string
