// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package nats

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each NATS replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="u1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Jetstream configuration.
	// +kubebuilder:default:={}
	Jetstream Jetstream `json:"jetstream"`
	// NATS configuration.
	// +kubebuilder:default:={}
	Config ValuesConfig `json:"config"`
}

type ValuesConfig struct {
	// Additional configuration to merge into NATS config.
	// +kubebuilder:default:={}
	Merge *k8sRuntime.RawExtension `json:"merge,omitempty"`
	// Additional resolver configuration to merge into NATS config.
	// +kubebuilder:default:={}
	Resolver *k8sRuntime.RawExtension `json:"resolver,omitempty"`
}

type Jetstream struct {
	// Enable or disable Jetstream for persistent messaging in NATS.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled"`
	// Jetstream persistent storage size.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
}

// +kubebuilder:validation:Enum="s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge"
type ResourcesPreset string
