// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package foundationdb

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Cluster configuration.
	// +kubebuilder:default:={}
	Cluster Cluster `json:"cluster"`
	// Storage configuration.
	// +kubebuilder:default:={}
	Storage Storage `json:"storage"`
	// Explicit CPU and memory configuration for each FoundationDB instance. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="u1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// Monitoring configuration.
	// +kubebuilder:default:={}
	Monitoring Monitoring `json:"monitoring"`
	// Custom parameters to pass to FoundationDB.
	// +kubebuilder:default:={}
	CustomParameters []string `json:"customParameters,omitempty"`
	// Container image deployment type.
	// +kubebuilder:default:="unified"
	ImageType ImageType `json:"imageType"`
	// Security context for containers.
	// +kubebuilder:default:={}
	SecurityContext SecurityContext `json:"securityContext"`
	// Enable automatic pod replacements.
	// +kubebuilder:default:=true
	AutomaticReplacements bool `json:"automaticReplacements"`
}

type Backup struct {
	// Enable backups.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Retention policy for backups.
	// +kubebuilder:default:="7d"
	RetentionPolicy string `json:"retentionPolicy"`
	// S3 configuration for backups.
	// +kubebuilder:default:={}
	S3 BackupS3 `json:"s3"`
}

type BackupS3 struct {
	// S3 bucket name.
	// +kubebuilder:default:=""
	Bucket string `json:"bucket"`
	// S3 credentials.
	// +kubebuilder:default:={}
	Credentials BackupS3Credentials `json:"credentials"`
	// S3 endpoint URL.
	// +kubebuilder:default:=""
	Endpoint string `json:"endpoint"`
	// S3 region.
	// +kubebuilder:default:="us-east-1"
	Region string `json:"region"`
}

type BackupS3Credentials struct {
	// S3 access key ID.
	// +kubebuilder:default:=""
	AccessKeyId string `json:"accessKeyId"`
	// S3 secret access key.
	// +kubebuilder:default:=""
	SecretAccessKey string `json:"secretAccessKey"`
}

type Cluster struct {
	// Fault domain configuration.
	// +kubebuilder:default:={}
	FaultDomain ClusterFaultDomain `json:"faultDomain"`
	// Process counts for different roles.
	// +kubebuilder:default:={}
	ProcessCounts ClusterProcessCounts `json:"processCounts"`
	// Database redundancy mode (single, double, triple, three_datacenter, three_datacenter_fallback).
	// +kubebuilder:default:="double"
	RedundancyMode string `json:"redundancyMode"`
	// Storage engine (ssd-2, ssd-redwood-v1, ssd-rocksdb-v1, memory).
	// +kubebuilder:default:="ssd-2"
	StorageEngine string `json:"storageEngine"`
	// Version of FoundationDB to use.
	// +kubebuilder:default:="7.3.63"
	Version string `json:"version"`
}

type ClusterFaultDomain struct {
	// Fault domain key.
	// +kubebuilder:default:="kubernetes.io/hostname"
	Key string `json:"key"`
	// Fault domain value source.
	// +kubebuilder:default:="spec.nodeName"
	ValueFrom string `json:"valueFrom"`
}

type ClusterProcessCounts struct {
	// Number of cluster controller processes.
	// +kubebuilder:default:=1
	ClusterController int `json:"cluster_controller"`
	// Number of stateless processes (-1 for automatic).
	// +kubebuilder:default:=-1
	Stateless int `json:"stateless"`
	// Number of storage processes (determines cluster size).
	// +kubebuilder:default:=3
	Storage int `json:"storage"`
}

type Monitoring struct {
	// Enable WorkloadMonitor integration.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled"`
}

type Resources struct {
	// CPU available to each instance.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each instance.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type SecurityContext struct {
	// Group ID to run the container.
	// +kubebuilder:default:=4059
	RunAsGroup int `json:"runAsGroup"`
	// User ID to run the container.
	// +kubebuilder:default:=4059
	RunAsUser int `json:"runAsUser"`
}

type Storage struct {
	// Size of persistent volumes for each instance.
	// +kubebuilder:default:="16Gi"
	Size resource.Quantity `json:"size"`
	// Storage class (if not set, uses cluster default).
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
}

// +kubebuilder:validation:Enum="unified";"split"
type ImageType string

// +kubebuilder:validation:Enum="s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge"
type ResourcesPreset string
