// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package mariadb

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of MariaDB replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each MariaDB replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="u1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// MariaDB major.minor version to deploy
	// +kubebuilder:default:="v11.8"
	Version Version `json:"version"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
}

type Backup struct {
	// Retention strategy for cleaning up old backups.
	// +kubebuilder:default:="--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
	CleanupStrategy string `json:"cleanupStrategy"`
	// Enable regular backups (default: false).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Password for Restic backup encryption.
	// +kubebuilder:default:="<password>"
	ResticPassword string `json:"resticPassword"`
	// Access key for S3 authentication.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey"`
	// S3 bucket used for storing backups.
	// +kubebuilder:default:="s3.example.org/mariadb-backups"
	S3Bucket string `json:"s3Bucket"`
	// AWS S3 region where backups are stored.
	// +kubebuilder:default:="us-east-1"
	S3Region string `json:"s3Region"`
	// Secret key for S3 authentication.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey"`
	// Cron schedule for automated backups.
	// +kubebuilder:default:="0 2 * * *"
	Schedule string `json:"schedule"`
}

type Database struct {
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges.
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type User struct {
	// Maximum number of connections.
	MaxUserConnections int `json:"maxUserConnections"`
	// Password for the user.
	Password string `json:"password"`
}

// +kubebuilder:validation:Enum="s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v11.8";"v11.4";"v10.11";"v10.6"
type Version string
